# Generated by Django 5.1.5 on 2025-02-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_follow_post_like_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="comment",
        ),
    ]
