# Generated by Django 5.1.3 on 2024-12-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comments_biddings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Biddings",
            new_name="Bidding",
        ),
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
