# Generated by Django 5.1.3 on 2024-12-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_biddings_bidding_rename_comments_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="name",
            new_name="title",
        ),
    ]
