# Generated by Django 5.1.3 on 2024-12-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_name_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mo", "Motors"),
                    ("Fa", "Fashion"),
                    ("Ho", "Home Garden"),
                    ("Co", "Collectables & Art"),
                    ("El", "Electronics"),
                    ("Sp", "Sports, Hobbies & Leisure"),
                    ("He", "Health & Beauty"),
                    ("Me", "Media"),
                    ("Bu", "Business, Office & Industrial Supplies"),
                    ("Ot", "Others"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
