# Generated by Django 5.1.3 on 2024-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to=""
            ),
        ),
    ]
