# Generated by Django 5.1.3 on 2024-12-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="auctions/"
            ),
        ),
    ]
