# Generated by Django 5.2.3 on 2025-06-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_near_me", "0003_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="types",
        ),
    ]
