# Generated by Django 5.2.4 on 2025-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_near_me", "0009_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
